### ISSUE TITLE
show "current page" and "total pages"

### ISSUE THREAD

**Issue by fkazemi5236** [gerhardsletten/react-reader#100]
Hi.
First question:
  How to display the current page and total pages?
Second question:
If the device is resized or device rotates, how can the pages be updated?

note: You may need to provide a more complete document about this package

**Comment by gerhardsletten** [comment]
@fkazemi5236 Please see Readme about this

[/gerhardsletten/react-reader#display-page-number-for-current-chapter](https://github.com/gerhardsletten/react-reader#display-page-number-for-current-chapter)
[/gerhardsletten/react-reader#limitations](https://github.com/gerhardsletten/react-reader#limitations)

In short, epubjs dont support this..
