### ISSUE TITLE
access to js script inside epub

### ISSUE THREAD

**Issue by fciannel** [gerhardsletten/react-reader#102]
Inside the epub I have put a javascript file that I need to load to do some stuff while I am reading the book. The file is inside the js directory and each chapter has a <script> link to it in the <head>. The question I have is how do I access to that script using react-reader? It seems like it's bypassed at the moment?

**Comment by gerhardsletten** [comment]
@fciannel This repo is a react wrapper for epubjs, and epubjs render the epub inside an iframe. You could look into epubjs issues to see if there are some answers there, but as far as I know there are security limitations both on what the iframe can do on the parent page and vica versa what the parent page can do inside an iframe
