### ISSUE TITLE
Highlight on Safari - Production

### ISSUE THREAD

**Issue by erickbank** [gerhardsletten/react-reader#109]
Even in react-reader example , when user tries to highlight in a safari browser on production , the console shows this message
and nothings happens.

Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

anyone who fixed this?

**Comment by gerhardsletten** [comment]
@erickbank Hi, you can add `allowScriptedContent` to allow scripts in iframes See https://github.com/futurepress/epub.js#scripted-content

```
<ReactReader
  epubOptions={{
    allowScriptedContent: true
  }}
/>
```
