### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ricardo5401** [gerhardsletten/react-reader#11]
Hi!!!
First, congratulations for you great job. My question is, how do I change the font size to epub?

**Comment by gerhardsletten** [comment]
@ricardo5401 See [#usage in READMe](https://github.com/gerhardsletten/react-reader#usage), there is a getRendition function where you can spesify a theme, think you should be able to override the font-size there

**Comment by ricardo5401** [comment]
Yes, I checked it. However, it runs only once and I always wanted access to it. Anyway I found a way to change the styles when the page was already displayed. I injected the style in the iframe document, it is not recommended but it works and I did not have to break anything of his work :D

**Comment by sunny8751** [comment]
Adding this prop to ReactReader worked for me: 
```
getRendition={(rendition)=>{
  rendition.themes.default({ "p": { "font-size": "32px"}})
}}
```
Documentation: http://epubjs.org/documentation/0.3/#themes
