### ISSUE TITLE
how to use  react-reader for arabic(rtl) ebook

### ISSUE THREAD

**Issue by AhmadNasary** [gerhardsletten/react-reader#112]
hello
hope are you doing will
I how to use this package for Arabic books. the Arabic book is reading from right to left site how can use this or not?

**Comment by gerhardsletten** [comment]
@AhmadNasary Have never worked with RTL, could you share a public example in a repo with this? Also I see that there is a lot of issues in epubjs for RTL, so I am not sure how well it support that either: https://github.com/futurepress/epub.js/issues?q=is%3Aissue+is%3Aopen+rtl+
