### ISSUE TITLE
Add classes to reader elements

### ISSUE THREAD

**Issue by simmondsty** [gerhardsletten/react-reader#113]
First of all, thank you for this great library.

Is it possible to add classes to individual elements such as toc buttons for a custom hover effect?

**Comment by gerhardsletten** [comment]
@simmondsty To avoid users to use a specific styling solution line styled-components it only use basic react style-tags, which don't support hover. You could try to reach elements by their type and nesting like:

```
.your-wrapper-outside-react-reader > div > button:hover {
  text-decoration: underline;
} 
```
Else your could re-create the reader-component your self, take a look at https://github.com/gerhardsletten/react-reader/blob/master/src/modules/ReactReader/ReactReader.js, in it you will see the `EpubView` component that renders the epub.js core stuff.

It could be that I should at some css classnames inside the reader to make it easier to accomplish this.

**Comment by simmondsty** [comment]
Thank you Gerhard, this resolves the issue, adding classes in the lib files worked perfectly.
