### ISSUE TITLE
Undefined ReactReaderStyle

### ISSUE THREAD

**Issue by caronchen** [gerhardsletten/react-reader#115]
> "react-reader"' has no exported member named 'ReactReaderStyle'.

```typescript
import {
  ReactReader,
  ReactReaderStyle
} from "react-reader";
```
<img width="191" alt="image" src="https://user-images.githubusercontent.com/150803/165984550-8e7b8201-dc22-4335-8a16-49ec363d0684.png">

```json
"react-reader": "^0.21.1"
```

**Comment by gerhardsletten** [comment]
@caronchen Thank, looks like the ts typefile did not match what was exported from the module. Should be fixed in `react-reader@0.21.2`
