### ISSUE TITLE
Arrows (and navigation) not working in React.StrictMode

### ISSUE THREAD

**Issue by agatumm420** [gerhardsletten/react-reader#116]
I'm using react-reader for my project, but arrows do not allow to get to another page of the book. Epub seems to be working fine, you can get to different places using chapters at the beginning of the book. Does anyone have any idea why that is going on?

**Comment by agatumm420** [comment]
Ok I checked and the location is actually changing but nothing new is being displayed. Why could that be?

**Comment by gerhardsletten** [comment]
@agatumm420 Still not solved? Try with the demo-book (https://react-reader.metabits.no/files/alice.epub) or share a example

**Comment by Lamarcke** [comment]
Also have the same problem, using the exacly same snippet on the README tutorial.

**Comment by Lamarcke** [comment]
Setting epub location on localStorage and then retrieving it on first render actually works, and the page changes, but the arrow keys don't change the epub page.

`const [location, setLocation] = useState<any>(
        localStorage.getItem("epub-location")
            ? localStorage.getItem("epub-location")
            : 2
    );

    const locationChanged = (location: any) => {
        localStorage.setItem("epub-location", location);
        // epubcifi is a internal string used by epubjs to point to a location in an epub. It looks like this: epubcfi(/6/6[titlepage]!/4/2/12[pgepubid00003]/3:0)
        setLocation(localStorage.getItem("epub-location"));
    };`

**Comment by gerhardsletten** [comment]
@Lamarcke Could you please publish an example where this is not working. Just checked [https://react-reader.metabits.no/](https://react-reader.metabits.no/) and arrow works for me.

**Comment by Gremash** [comment]
I am having the same problem and just created a sample project with the issue: [https://github.com/Gremash/react-reader-test](https://github.com/Gremash/react-reader-test)

**Comment by gerhardsletten** [comment]
@Gremash @Lamarcke Did have a look at the sample repo now, and looks like you need to remove `<React.StrictMode>` in index.js.

Have to look more into this after vacation how to make the component support strict mode..

**Comment by Lamarcke** [comment]
Thank you for your time. I hasn't expecting something like this, but i'm
glad there's a way to use your library in my project now, thanks.

Em qua, 20 de jul de 2022 18:59, Gerhard Sletten ***@***.***>
escreveu:

**Comment by azu** [comment]
I've submit PR to fix this issue #123

**Comment by gerhardsletten** [comment]
@azu Published in react-reader@0.21.3
