### ISSUE TITLE
Part of page become hidden

### ISSUE THREAD

**Issue by darkojelen** [gerhardsletten/react-reader#118]
While doing on my project I notice that when I click on "Use full browser window", text slide up, but bottom stay blank.  Bottom text in height of header become invisible and it is missing. I need to go to first page with arrow buttons and after that problem disappear. I check also with your demo and it behaves similar.
Div with class epub-view and iframe with id="epubjs-view …" do not get correct height in Inline Styles after click on »Use full browser window«.
![demoepub](https://user-images.githubusercontent.com/28961283/172917154-85bd7c71-267d-4d7e-bf3e-a819feef26ba.jpg)

**Comment by gerhardsletten** [comment]
@darkojelen Should work now
