### ISSUE TITLE
document's frame is sandboxed and the 'allow-scripts' permission is not set - SAFARI

### ISSUE THREAD

**Issue by avalero** [gerhardsletten/react-reader#124]
On safari, when clicking on a TOC link the following message appears on the console 
```
Blocked script execution in '___TOC link____' 
because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (x13)
```
In other browsers it works just fine

**Comment by johnfactotum** [comment]
You'll need to set `allowScriptedContent` to `true` in `epubOptions`. See https://github.com/futurepress/epub.js/blob/v0.3.93/README.md#scripted-content.

For reference, I believe the WebKit bug is https://bugs.webkit.org/show_bug.cgi?id=218086.

**Comment by avalero** [comment]
Great. It works
