### ISSUE TITLE
NextJS - META-INF/container.xml 404 (Not Found)

### ISSUE THREAD

**Issue by michaldev** [gerhardsletten/react-reader#125]
Hi. I have problem with using this library on NextJS distribution of reactjs.

PDF: https://react-reader.metabits.no/files/alice.epub

I got error:
`GET http://localhost:3000/META-INF/container.xml 404 (Not Found)`

I used dynamic for loading "non-ssr" library, like this:
```
  const DynamicComponentWithNoSSR = dynamic(() => import('../components/nossr/ebook-viewer'), {
    ssr: false
})
```

Full example here:
https://github.com/michaldev/example-with-nossr-react-reader/

![Zrzut ekranu z 2022-09-20 13-00-46](https://user-images.githubusercontent.com/5132385/191242466-34273812-5551-4ea7-bfc1-eeb9a924acba.png)

**Comment by gerhardsletten** [comment]
@michaldev Did tried your repo, and one thing was that you did not set a height for the viewer, adding this, and you will see the epub:

```ts
import { FunctionComponent } from "react";
import { ReactReader } from "react-reader";

type EbookViewerProps = {
  url: string;
};

const EbookViewer: FunctionComponent<EbookViewerProps> = ({ url }) => {
  return (
    <div
      style={{
        height: "100vh",
        width: "100vw",
      }}
    >
      <ReactReader
        url={url}
      />
    </div>
  );
};

export default EbookViewer;
export type { EbookViewerProps };

```

When it comes to the 404 on `META-INF/container.xml` take a look at [this thread from epubjs issues](https://github.com/futurepress/epub.js/issues/289). I wonder if nextjs does some magic while serving assets, and if that is interfering with epubjs trying to load ressources

**Comment by gerhardsletten** [comment]
@michaldev Did open an PR on your example where its running
