### ISSUE TITLE
Cannot open links from ePub

### ISSUE THREAD

**Issue by avalero** [gerhardsletten/react-reader#131]
Hello,

When loading an epub with an external link (`target=_blank`) I get the following error on Firefox/Safari/Chrome console
```
Blocked opening '<URL>' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```
and the link does not open.

I have looked for a prop to configure this behaviour, but I have not found any on the `RenditionOptions` interface. 

If I right click on the links and click "Open on a new..." it works just fine.

**Comment by gerhardsletten** [comment]
@avalero You need to add allowPopups, [see PR from epubjs here](https://github.com/futurepress/epub.js/pull/1249)

```
<ReactReader
  epubOptions={{
    allowPopups: true
  }}
/>
```
