### ISSUE TITLE
bookmarks support

### ISSUE THREAD

**Issue by mogadanez** [gerhardsletten/react-reader#133]
is it supported? seems nested library have it.
https://github.com/futurepress/epub.js/search?q=bookmark&type=commits
any ideas how to  implement  this functionality with react-reader?

**Comment by gerhardsletten** [comment]
@mogadanez Did you look at [the example here](https://github.com/gerhardsletten/react-reader#hightlight-selection-in-epub), you will also need to make your own reader by copy [ReactReader.js](https://github.com/gerhardsletten/react-reader/blob/master/src/modules/ReactReader/ReactReader.js) into your project, and add your own GUI to bookmark the current page
