### ISSUE TITLE
react-reader automatically splits book into chapters

### ISSUE THREAD

**Issue by vstrelianyi** [gerhardsletten/react-reader#140]
Steps to reproduce
- I have opened a book with 100+ pages 
- Initially this book does not have any chapters
- I observe renditionRef.current.location object on event: 'locationChanged' - and after every 30-40 pages it shows a new object - which means is a new chapter

**Comment by gerhardsletten** [comment]
@vstrelianyi Have you tried to unzip the epub to check its contents? See that the toc menu is not showing nested chapters, so it could be nested chapters below that the gui is not showing.

**Comment by vstrelianyi** [comment]
Hi!
toc - has only one chapter ( as far as I understand there should be on chapter by default )
and there is only one xhtml file with content for that ( it has all the content from my book )

but react-reader does not show all content as one chapter. it adds more chapters ( they are not shown in the toc navigation, but according to book object it is so )

**Comment by gerhardsletten** [comment]
@vstrelianyi Then it is the underlaying https://github.com/futurepress/epub.js/ that is splitting up big chapters for performance maybe

**Comment by vstrelianyi** [comment]
ok, got , thx

**Comment by vstrelianyi** [comment]
@gerhardsletten I have checked the epubjs lib - it splits the imported book into locations
they are a part of book object
![image](https://user-images.githubusercontent.com/15492290/212369388-80eb93e0-12f1-4400-8f52-a77b37d30057.png)

**Comment by gerhardsletten** [comment]
@vstrelianyi This library just wraps epubjs
