### ISSUE TITLE
Images not replaced with blob urls. Rather it has relative urls.

### ISSUE THREAD

**Issue by AjayManikantaG** [gerhardsletten/react-reader#142]
Hi Team,

I have tried to load epub with the url "_https://files-au-prod.cms.commerce.dynamics.com/cms/api/qsjhkgqqvf/binary/MK1Lgj_". The images for some pages are not getting loaded with blob urls. Could you please let me know if the epub is wrong or i am missing something here.

Thanks,
Ajay

**Comment by gerhardsletten** [comment]
@AjayManikantaG Was not able to download your epub-file, but it could be that the internal html use external url's in the img-tags. Else the render of the epub-content is done by epub-js and that you need to check that repo. Also try googling "validate epub" to find tools to validate your epub-files

**Comment by AjayManikantaG** [comment]
[let’s play!_alice patrick - Copy.zip](https://github.com/gerhardsletten/react-reader/files/10878714/let.s.play._alice.patrick.-.Copy.zip)

@gerhardsletten  I have provided the zip file. Could you please change .zip to .epub to change to epub file.

I have checked the image files in html. Those are mapped correctly. Can you please check once if possible. Let me know your comments and suggestions of how can resolve this issue.

I am suspecting the image names to be an issue. Please suggest me if I am thinking in a right direction.

**Comment by gerhardsletten** [comment]
@AjayManikantaG You can run `unzip <name>.epup` to see the contents of the epub. And it looks like the image-paths are broken:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/63344/222673880-7b2a19e9-f166-4b53-a7de-c5baf9bbdbbe.png">

**Comment by AjayManikantaG** [comment]
@gerhardsletten Thanks a lot. I will rectify those.
