### ISSUE TITLE
How to highlight the text when open epub file?

### ISSUE THREAD

**Issue by leowucn** [gerhardsletten/react-reader#143]

**Comment by leowucn** [comment]
I have some text list, and I want to auto hightlight the text when opening epub file? Is there any way to do this. Thanks.

**Comment by gerhardsletten** [comment]
@leowucn Take a look at the recipe for[ collecting user highlights](https://github.com/gerhardsletten/react-reader#hightlight-selection-in-epub). You can use the `getRendition` callback prop to just add an annotations but you need to find the right cfiRange to pass in:

```
renditionRef.current.annotations.add(
          'highlight',
          cfiRange,
          {},
          null,
          'hl',
          { fill: 'red', 'fill-opacity': '0.5', 'mix-blend-mode': 'multiply' }
        )
```

**Comment by leowucn** [comment]
Ok, Thanks.
