### ISSUE TITLE
Clicking on the title in the directory does not navigate to the corresponding section.

### ISSUE THREAD

**Issue by leowucn** [gerhardsletten/react-reader#148]
I tried several examples on the homepage, but why can't I jump to the corresponding section when I click on the title in the directory?

**Comment by kartikarcot** [comment]
Hi! I have the same issue as well. @gerhardsletten can you help us out with this? clicking on sections in the TOC does not take us to those sections

**Comment by gerhardsletten** [comment]
@leowucn or @kartikarcot For me it [works in the demo](https://react-reader.metabits.no/). Can it be related to the epub you are trying to display?

<img width="802" alt="image" src="https://user-images.githubusercontent.com/63344/233864117-de5a948e-1952-4a45-aeb9-68e0716a4826.png">

**Comment by kartikarcot** [comment]
Hmm maybe it was my browser acting up. It seems to work now. Sorry about the confusion
