### ISSUE TITLE
Total pages is wrong on reload

### ISSUE THREAD

**Issue by kartikarcot** [gerhardsletten/react-reader#153]
I tried following the logic given in the readme to add page number support for my app. However with that implementation when I reload the total pages always seems to be 2. However when I switch chapters it quickly gets fixed. Is there any reliable way of letting the user know of the progress made in the ebook? It's fine even if it's loc based like the one you get in kindle app.

**Comment by gerhardsletten** [comment]
@kartikarcot As mentioned there: "Also see limitation for pagination for the whole book"

[Limitations](https://github.com/gerhardsletten/react-reader#limitations)

> EpubJS will need to render the current chapter before it will now how many pages it will have in the current viewport. Because of this it will not be able to tell you at which page in the whole epub-book you are at, nor will you be able to get the total pages for the whole book
