### ISSUE TITLE
in vertical Scroll view : when I click any section in TOC it 1st open that section and in next second it scrolled to end of that section. same happens When I pass externally epubcfi of the start of the section. 

### ISSUE THREAD

**Issue by junior-g** [gerhardsletten/react-reader#155]
I observed that in vertial scroll locationChanged function being called twice. and 1st it give expected start epubcfi and then 2nd time (after auto scroll) it gives end epubcfi

**Comment by junior-g** [comment]
I tried this also - https://github.com/futurepress/epub.js/issues/1131. 
It's the same issue
after trying this issue confined to some sections of the book only but behaviour remains same for cases when I am manually putting start epubcfi location of the section

**Comment by junior-g** [comment]
https://github.com/futurepress/epub.js/issues/1131. this worked when I set offset to zero by sending offsets in this way 
 <ReactReader
 ......
 epubOptions={{
                            allowScriptedContent: true,
                            allowPopups: false,
                            flow: "scrolled",
                            manager: 'continuous',
                            offset: 0
                        }}
 />

**Comment by junior-g** [comment]
@gerhardsletten Can you help here -

**Comment by junior-g** [comment]
> @gerhardsletten , @rafaelsaback , @Lamarcke , @azu Can you help here -

*BUMP*

**Comment by rafaelsaback** [comment]
`react-reader` uses `epubjs` under the hood. If this is an issue in `epubjs`, then it must be fixed there. After they have this bug patched, then someone can try upgrading the version of `epubjs` used here in `react-reader`.

Disclaimer, I'm not a maintainer of this repo

**Comment by gerhardsletten** [comment]
@junior-g When I looked at this, it looks like the bug only happens on the first click on the chapther-link, if you click the same chapter one more time, it scrolls to the right location.

Look like a bug in epubjs, as mentioned in https://github.com/futurepress/epub.js/issues/1131.

When I revert this change https://github.com/futurepress/epub.js/commit/915ab2e107f7d95d44a9fbc48b91409c6ac8c3e2 it is working as expected.

You could try to just fixed that in your node_modules If you build the code locally, or search the web for how to replace a nested dependency within node_modules for your bundler.
