### ISSUE TITLE
How to navigation to spesfic page ?

### ISSUE THREAD

**Issue by mohammadtaheri30132** [gerhardsletten/react-reader#157]

**Comment by gerhardsletten** [comment]
@mohammadtaheri30132 You will need to know the cfi-location you want to navigate to. The `tocChanged` callback will give you all chapters, this list will contain the cfi-location for each chapter. I you console.log the `locationChanged` prop you will also see what is the current location that is displayed. Take a look at the [basic-usage](https://github.com/gerhardsletten/react-reader#basic-usage)

**Comment by mohammadtaheri30132** [comment]
thank you @gerhardsletten
