### ISSUE TITLE
How to know the reading percentage of the book?

### ISSUE THREAD

**Issue by leowucn** [gerhardsletten/react-reader#158]
I can get an epubcfi of current location, but how to know the reading percentage of the whole book? Is there any way to compute it ? Thanks.

**Comment by gerhardsletten** [comment]
@leowucn See first bullet in https://github.com/gerhardsletten/react-reader#limitations

> EpubJS will need to render the current chapter before it will now how many pages it will have in the current viewport. Because of this it will not be able to tell you at which page in the whole epub-book you are at, nor will you be able to get the total pages for the whole book
