### ISSUE TITLE
The percentage in location does not update if you change location from TOC too fast

### ISSUE THREAD

**Issue by shiroyasha9** [gerhardsletten/react-reader#166]
Hey, great work on the library. This might seem like a duplicate of #158, but hear me out. The rendition object that is provided by the `getRendition` prop gives you an event listener for location. The location object has 2 attributes - `start` and `end`. Inside them both, you get a percentage float which ranges from 0 at the start of the book, and 1 at the end of the book. 

Here is how I am using it.
```tsx
  const handleRendition = (rendition: Rendition) => {
    rendition.on('relocated', (location: Location) => {
      setCurrentBookPosition(
        Number((location.start.percentage * 100).toFixed(1))
      );
    });
  };
```

Location object for context
<img width="313" alt="image" src="https://github.com/gerhardsletten/react-reader/assets/148140610/e4447b07-1f41-4f22-9955-edbf0fe47292">

The problem I am encountering is that once the epub loads, if you immediately go to a different page using table of contents, the `location` object does not update, and the `percentage` and `location` are both 0 in start and end. The event listener is triggered, but the values are not updated.

<img width="441" alt="image" src="https://github.com/gerhardsletten/react-reader/assets/48734821/610bfa3a-f78f-4f49-9800-6a9f4e6722a2">

It gets fixed if you wait for some time before navigating using TOC or between different pages without it. 

Is there a way to fix this so that the location object gets the correct values at all times? I have read the limitations, but I could not understand how it relates to this particular issue. Open to assisting in any way I can, and thanks for your help!

**Comment by gerhardsletten** [comment]
@shiroyasha9 Your digging into the inner stuff of [futurepress/epub.js)](https://github.com/futurepress/epub.js) so you might have a better luck see how the`percentage` get set in that repo.

To me percentage is always 0 with the alice-book in this repo. Might be better do use displayed object and calculate this yourself.
