### ISSUE TITLE
Prefetch Next Page.

### ISSUE THREAD

**Issue by kiranavaibe** [gerhardsletten/react-reader#170]
Hey Gerhard,
Thanks for the package! Is there a way to speed up the loading of the next page in the EPUB? It's a bit slow currently.

**Comment by gerhardsletten** [comment]
@kiranavaibe if you take a look at the epubjs iframe within the dom you will see that the whole chapter is loaded and displayed as separate pages with css-column. So clicking the next page only change the x-position so the current page is visible. And there is not anything that gets loaded for this.

<img width="1421" alt="image" src="https://github.com/gerhardsletten/react-reader/assets/63344/c50d0993-590e-4ca1-8914-151a3ba1e2bb">
