### ISSUE TITLE
Adjusting to window/container size happening only on chapter change

### ISSUE THREAD

**Issue by Shultc** [gerhardsletten/react-reader#175]
When you changing size of container/window, text columns and pages resized only when you navigate between chapters. 
Would be nice to make it on each container resize, or have function to do it manually.
![image](https://github.com/gerhardsletten/react-reader/assets/458282/0b3601ab-c765-49ba-84a2-6b0750a59310)
![image](https://github.com/gerhardsletten/react-reader/assets/458282/8050524f-83fb-4e28-954c-b728b16b6a1d)

**Comment by Shultc** [comment]
> @Shultc If I resize my browser window for the demo: https://react-reader.metabits.no/ the columns resize, does this not happen for you?

Interesting.... In the demo it happening to me. And according to source code of demo — automatically. 
But in my code (pseudo windows) I was able to achieve same result only by adding this code to resize event:

```JavaScript
renditionRef.current?.resize('100%', '100%');
```

**Comment by gerhardsletten** [comment]
@Shultc Can you make a samle repo for this case?
