### ISSUE TITLE
Overriding Reader Fonts

### ISSUE THREAD

**Issue by alphonso06** [gerhardsletten/react-reader#177]
## Summary
I'm trying to use custom fonts, both from the source directory and fonts from Google (mostly as a test to see if it will work).

I read both [this issue](https://github.com/gerhardsletten/react-reader/issues/95) and [this one](https://github.com/futurepress/epub.js/issues/788). ~~Based from experience (local machine), I tried using the same Open Dyslexic font which is **not installed** on my Windows machine, and found that it works.~~

![image](https://github.com/gerhardsletten/react-reader/assets/43776043/d2eb6482-910e-49bb-b935-818c8015a284)

However, using any other fonts that aren't considered _web-safe_ results in the default Times New Roman typeface. Similar case for my Linux machine. All mobile test devices simply don't change fonts at all.

## Example Project
[This example project](https://stackblitz.com/edit/vitejs-vite-zwabcj?file=src%2FApp.tsx) is configured to attempt to use the custom `Ubuntu Mono` font from Google.

Currently it only displays Times New Roman on all my desktop machines, and refuses to change on mobile devices.

## Possible Solutions
I'm not sure if it's viable to surgically insert the custom font into every `.epub` file that requires _non-web-safe_ typefaces. Good alternative might be to just use _web-safe_ fonts, but I might not have this luxury.

Anyway, I'd love to know if I missed anything, or if I could improve the implementation.

--**EDIT**--
I found that I actually had the Open Dyslexic font installed on my Windows machine. It's now back to Times New Roman when changing fonts.

**Comment by alphonso06** [comment]
It might be possible to apply fonts via CDN as demonstrated [here](https://github.com/pgaskin/ePubViewer/blob/5b4d4990350d0548a7634b7a4d95aa0f39e262ab/script.js#L463).

Though I attempted to do the same in the stackblitz sample project, the Rendition's document body seems to be undefined, causing a white screen of death.

```ts
// In the getRendition prop of ReactReader
let el = _rendition
            .getContents()
            .document.body.appendChild(
              _rendition.getContents().document.createElement('link')
            );
          el.setAttribute('rel', 'preload');
          el.setAttribute('as', 'font');
          el.setAttribute('type', 'font/woff');
          el.setAttribute('crossorigin', 'anonymous');
          el.setAttribute(
            'href',
            'https://fonts.cdnfonts.com/s/29616/open-dyslexic.woff'
            );
```

**Comment by gerhardsletten** [comment]
@alphonso06 

Adding fonts to a html document require that you add a [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) tag, and not just loading the font-file.

[Added an example for this here](https://react-reader.metabits.no/custom-font)

[Source code](https://github.com/gerhardsletten/react-reader/blob/main/src/examples/CustomFont.tsx)

**Comment by naresh-intra** [comment]
Tried the example, but it doesn't seem to apply the OpenDyslexia font to the reader content

**Comment by gerhardsletten** [comment]
It should look like this:

<img width="788" alt="image" src="https://github.com/gerhardsletten/react-reader/assets/63344/4a7425ed-4cb4-42de-a972-bba83f19c4cb">

**Comment by naresh-intra** [comment]
<img width="696" alt="Screenshot 2024-06-21 at 2 46 12 PM" src="https://github.com/gerhardsletten/react-reader/assets/121652672/34b18e00-bfeb-4d92-82a7-0c36adce3c9a">
It doesn't seem to apply. Arial renders fine. Am i missing something?

**Comment by gerhardsletten** [comment]
Strange, works in both Chrome, Safari and Firefox here. Do you see any errors in your console?

Also, check your network-tab to check if the font is loading there

<img width="1259" alt="image" src="https://github.com/gerhardsletten/react-reader/assets/63344/8ba5f625-427a-4902-b67e-1edaa652769e">

**Comment by naresh-intra** [comment]
The font download is failing with 403

<img width="1132" alt="Screenshot 2024-06-21 at 3 08 29 PM" src="https://github.com/gerhardsletten/react-reader/assets/121652672/f11f01f1-bd87-4fcb-b064-611ce8448686">

I tried on multiple systems/browsers and mobile browser as well

**Comment by gerhardsletten** [comment]
Okay, I have moved the font into the repo so its loaded from the same server as the demo, do it work now?

**Comment by naresh-intra** [comment]
ya the example works now, thanks!
