### ISSUE TITLE
How to get a list of all pages given the current device resolution?

### ISSUE THREAD

**Issue by kimpers** [gerhardsletten/react-reader#18]
Hi,

I am trying to implement a slider allowing the user to go back and forth between the pages in the book, I also want to display a progression indicator for how far they have read.

With the vanilla `epub.js` this seems rather easily achievable according to their example, however I am not able to reproduce this in `react-reader`. Is there support for doing this in `react-reader`?

Thanks for a great library 👍

**Comment by gerhardsletten** [comment]
Hi @kimpers thanks!

If you look at [the example](https://github.com/gerhardsletten/react-reader#usage) and the `getRendition` function, this will give you the core epub-js object, you will have to look into it.

By the way, in which example of epub-js did you found this? Could you paste the link, and I will take a look also.

**Comment by kimpers** [comment]
Hi @gerhardsletten, sorry for the late reply. I missed the notification of you answering this.

So what I am trying to do is have a slider for navigating between pages. Like this example from epubjs: https://github.com/futurepress/epub.js/blob/master/examples/pagination.html

The problem is that I can't seem to get a list of pages so I know where to navigate when the user moves the slider an arbitrary number of steps.

I have studied the information available in `getRendition` but can't seem to find anything useful for solving this problem.

**Comment by gerhardsletten** [comment]
Hi @kimpers, that example is from the master-branch of epubjs, but its the v0.3 which we can use, because it adds modular structur, and in that branch not everything that is in master is implemented. Also I  epubjs in only aware of the number of pages after it has rendered a chapter, so you would need to do a pre-render of each chapter in a book, or guess each chapters based of content-length of each chapter.

**Comment by kimpers** [comment]
@gerhardsletten  so if I understand you correctly then having a slider for switching pages like this will not be doable with `react-reader`?

**Comment by gerhardsletten** [comment]
Yes, think its kind of hard to get it right with web-technologies, the example you linked above dont work very good either: [futurepress.github.io/epub.js/examples/pagination.html](http://futurepress.github.io/epub.js/examples/pagination.html)

You would need a backend node server, with a headless browser that would need to compute each chapter in the exact window-size of the users device.

**Comment by kimpers** [comment]
Thanks for the feedback. What about a continuous scrolling solution. Ignoring pages and just making the ebook a long fluid scrolling experience. Would that work with `react-reader`?

**Comment by gerhardsletten** [comment]
Think they have a regular scrolling option, but it is still for only one chapter at the time. You have a `epubOptions` in react-reader, and that is passed to the epubjs's rendition-object, take a look here:

[github.com/futurepress/epub.js/blob/v0.3/src/rendition.js#L34](https://github.com/futurepress/epub.js/blob/v0.3/src/rendition.js#L34)

I have seen some authors publishing the whole book in one chapter, and its expensive performance-wise so this will make older, mobile devices wait for a while before becoming responsive again.

React-reader is mostly a think wrapper, so please take a look at [epubjs v0.3](https://github.com/futurepress/epub.js/tree/v0.3) and what it support, and if you need access some other underlaying api in it, you could send a PS or discuss it here if someone else what to take a look at it.

**Comment by kimpers** [comment]
Thanks for the help @gerhardsletten, I'll close this issue now and evaluate my options
