### ISSUE TITLE
fetch epub pages 5 to 5 (with pagination) 

### ISSUE THREAD

**Issue by mostafashariaat** [gerhardsletten/react-reader#181]
Is there a way to not load all the pages of epub at once and for example 5 to 5 are loaded In the link below, there was a problem 
(https://github.com/gerhardsletten/react-reader/issues/170)
,according to which I found out that all the pages of the epub are loaded at once, and if the epub is long, it will slow down its initial loading.

**Comment by gerhardsletten** [comment]
@mostafashariaat Nope, this is how the book-projection in epubjs work, it lays out the content in [css-columns](https://developer.mozilla.org/en-US/docs/Web/CSS/columns) and then calculate the number of pages in a chapter by the total width divided by screen width.

If you try to unzip a epub you will see that each chapter is a separate html-files, but some publishers / authors put the whole book in one chapter / file. Most books is text only so it should not be to heavy on performance, but if the book contains a lot of images that could require more memory. One thing you try then is to override the browsers dom-parser and add a loading="lazy" on img-tags, take a look at this recipe:

https://github.com/gerhardsletten/react-reader?tab=readme-ov-file#handling-not-valid-epub-files
