### ISSUE TITLE
Toc redirection is not working

### ISSUE THREAD

**Issue by mira-thakkar** [gerhardsletten/react-reader#19]
I have installed this package and trying to implement react reader with the given example file.Next and previous page functionality is working properly, but nothing happens on TOC item click. I also want to get the page number or some indicator that shows how far the user has reached on completing the book. 
```
 import React, {Component} from 'react';
 import { ReactReader }  from 'react-reader';

 class Book extends Component { 
        constructor(props) {
             super(props);
        }

         getRendition = (rendition) => {
               // Get access to core events from epubjs
               rendition.on('selected', this.onRenditionSelection)
              // Add custom styles
              rendition.themes.default({
                      '::selection': {
                           'background': 'rgba(255,255,0, 0.3)'
                      }
              })
        }

        render(){
            return (
                  <div>
                   <div style={{height:'400px', position:relative'}}> 
                    <ReactReader
                        url={'https://s3-eu-west-1.amazonaws.com/react-reader/alice.epub'}
                        title={'Alice in wonderland'}
                        locationChanged={(epubcifi) => console.log(epubcifi)}
                        getRendition={this.getRendition}
                      />
                   </div>
                  </div>
            );
      }
}

export default Book;
```
On location change, i have log it on the console, that shows it like 'Chapter_001.xhtml', 'Chapter_002.xhtml', where as on next/previous click it shows diff format of location.
how can i fix it? 
Thanks!

**Comment by gerhardsletten** [comment]
Hi @mira-thakkar, not sure why the toc-button is not working in your code. Could you download this repo and run the demo `npm i && npm start` and see if it works there? 

Also the way epubjs work, is that is take the html-content of the current chapter and draw it inside an element with css-columns, it then figur out what this elements with is and calculate the number of pages based on that. So you should find it somewhere deep down in the epubjs's rendition object I think. See the Usage section in README.md

**Comment by mira-thakkar** [comment]
@gerhardsletten It worked

**Comment by ahmdichsan** [comment]
@mira-thakkar, did you find solution to your problem? I encounter the same issue and the same requirement as yours. When I click one of the chapter on the left side (toc), its just close the side bar (toc). I also need to show the current page information. Moreover, when I open the epub, its not start from the beginning. I am using:

```
"react": "^17.0.1",
"react-reader": "^0.20.3"
```

**Comment by ahmdichsan** [comment]
Sorry, mybad, I forgot to maintain the ```location``` state. All is well now. But I still couldn't figure out how to show the current page. If anyone have a working example, please share it. Thank you.

**Comment by gerhardsletten** [comment]
@ahmdichsan For page number, take a look at getRendition callback in [the example](https://gerhardsletten.github.io/react-reader/) there is a location->displayed object which you can use to see the current page of the current chapter. Note that epubjs will only be able to give you page numbers of the current chapter, because it needs to render it before it will know how many pages it will take up for the height/width of the browser-window

![image](https://user-images.githubusercontent.com/63344/111960745-6a970b80-8af0-11eb-97f8-6ca4efa636e3.png)
