### ISSUE TITLE
Multipart ePub

### ISSUE THREAD

**Issue by evivz** [gerhardsletten/react-reader#20]
Hello, Is there anyway to read multipart epub?

What i mean is I have epubs with multiple chapters and each as single single epub. But I want to show them as one runtime. Is it possible with this reader?

**Comment by gerhardsletten** [comment]
Dont think so, you would typically need to build a book-shelf yourself, and then use react-reader to display the current e-pub file. Take a look [at this page](http://bokhylla.elevforlaget.no/#/) (which used react-reader)
