### ISSUE TITLE
Does not render on Firefox Quantum

### ISSUE THREAD

**Issue by kimpers** [gerhardsletten/react-reader#21]
React-reader does not seem to render when using the newest Firefox Quantum (OSX)

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/5450545/33401988-806bf946-d55b-11e7-9b29-d1d28a3e07dd.png">

Reproduction steps:
1. Visit https://gerhardsletten.github.io/react-reader/ with Firefox Quantum

**Comment by mira-thakkar** [comment]
@gerhardsletten I am also getting the same issue on firefox, have checked on both 56.0 and 57.0(Quantom) version.
@kimpers do you get any solution for this ?

**Comment by gerhardsletten** [comment]
Hi, there have been some months since I pulled epubjs latest updates from v0.3 branch, but now I have switch back to use the epubjs package directly (did use a custom fork because there use to be some strange updates which breaked this library). It now works in FF for me.

**Comment by gerhardsletten** [comment]
Have published 0.16.1 to npm..

**Comment by kimpers** [comment]
Working fine on Quantum now.  🎉  Thanks @gerhardsletten
