### ISSUE TITLE
Ugllify Js error on building  app while using react-reader dependency

### ISSUE THREAD

**Issue by mira-thakkar** [gerhardsletten/react-reader#22]
I am using react-reader for Epub reader in my app, It works fine while i run the app like "node server.js" but it fails when i create the build of the app. I am getting error like
` "Unexpected token name «of», expected punc «;»" `
 I have checked by removing import of react-reader and app build works fine.This was working fine in previous  version of react-reader.
can anyone help me with this uglifyjs issue?

**Comment by gerhardsletten** [comment]
Sorry, but this is a problem with [fchasen/marks](https://github.com/fchasen/marks), its is not correctly transpilled to es5. Maybe you could create a issue/pull request there to fix it?

Else you will have to disable uglify or include that library webpack babel rule.

**Comment by kimpers** [comment]
I made a temporary workaround for this by adding the below lines to my webpack prod config
```javascript
 ocess JS with Babel.
{
  test: /\.(js|jsx)$/,
  include: [
    paths.appSrc,
    path.resolve(paths.appNodeModules, 'epubjs'), // Add this
    path.resolve(paths.appNodeModules, 'marks-pane') // Add this
  ],
  loader: require.resolve('babel-loader'),
  options: {

    compact: true
  }
},
```
This is only an intermittent fix and should not be used permanently

**Comment by mira-thakkar** [comment]
@kimpers Thanks!
