### ISSUE TITLE
epubjs dependency breaks `react-scripts build`

### ISSUE THREAD

**Issue by Ken-2scientists** [gerhardsletten/react-reader#26]
I just started using the `ReactReader` component in an app today for the first time, and I was thrilled at how quickly I was able to start to render ePubs. So, thanks for putting this out there!

I encountered an issue, though, when I attempted to build the app to deploy it. I'm working with an app generated via [create-react-app](https://github.com/facebook/create-react-app), with `react-scripts 1.1.0`. 

The build errors out with the output:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/epubjs/src/utils/core.js:71 

Read more here: http://bit.ly/2tRViJ9
```

That link suggests that the issue is that the epubjs library hasn't provided an ES5 version of their library. I haven't looked into epubjs before now, but it looks to me like the migration to ES6 is something they were doing on the v0.3 branch, which I see that `react-reader` uses, while the current released version (at least on npm) is still v0.2

So, maybe this ought to be an issue filed against that lib, but I thought I'd raise it here first to see if anyone else had encountered this when using `react-reader`.

**Comment by gerhardsletten** [comment]
Hi @Ken-2scientists 

Thanks, there are issues with the underlaying epubjs library and it has been discussed before see #22 

But I did publish and updated version of react-reader using epubjs/lib/index because its package.json module field pointing to code that is not correctly transpiled. Let me know if that fixes your issues
