### ISSUE TITLE
Imports failing

### ISSUE THREAD

**Issue by gunningham** [gerhardsletten/react-reader#29]
We're getting the following:

`(function (exports, require, module, __filename, __dirname) { import EpubView from ‘./EpubView/EpubView’;
^^^^^^
SyntaxError: Unexpected token import`

When we build to development with version 0.17. Believe it's something to do with this line:
`const modules = NODE_ENV === 'production' ? false : 'commonjs'`

Version 0.16.7 works but we also need the latest epubjs version which is not included with 0.16.7.

**Comment by gerhardsletten** [comment]
Hi, @gunningham 

Thats from the `.babelrc.js` file, do you do some custom inclusions of the library? Like `npm link react-reader` from a local clone? 

Just published a new version `react-reader@0.17.1` where the `.babelrc.js` file is added to the npmignore file so you could try with that one.
