### ISSUE TITLE
Scrolling 

### ISSUE THREAD

**Issue by tylerwhipple** [gerhardsletten/react-reader#31]
Hello and thank you for all your work on this project. 

I was wondering if it was possible to use a continuous scrolling view?

I keep trying to change the epuboptions, but to no avail. Is it possible with this or do I need to do something with the epub.js?

**Comment by niponchi** [comment]
This works for me.

```
<ReactReader
  url={'https://s3-eu-west-1.amazonaws.com/react-reader/alice.epub'}
  locationChanged={this.onLocationChanged}
  title={'Alice in wonderland'}
  location={location}
  getRendition={this.getRendition}
  epubOptions={{
    manager: "continuous",
    flow: "scrolled"
  }}
/>
```
reference: https://github.com/futurepress/epub.js/blob/master/examples/continuous-scrolled.html
