### ISSUE TITLE
Error: No Section Found

### ISSUE THREAD

**Issue by Javierenrique00** [gerhardsletten/react-reader#33]
Hello, running the project without making changes in the code I found the following error while executing the app in the console:

rendition.js:392 Uncaught (in promise) Error: No Section Found
    at Rendition._display (rendition.js:392)
    at Queue.dequeue (queue.js:99)
    at queue.js:153

I changed epubjs version to see if it solved the problem and the same. Do you know what could be the problem ?
PD:  at first the project do not worked and I had to change webpack-cli version to 3.1.1 to get it to work. but I think that this has not been related with the problem.

**Comment by kozec** [comment]
https://github.com/futurepress/epub.js/issues/684#issuecomment-495931737

**Comment by Ved111** [comment]
I am getting the same error and am not able to find the solution.
I looked up to @kozec 's solution but I am not able to understand where I should add that code snippet. 
Struggling with this error for more than 24 hours, any help will be appreciated.

**Comment by gerhardsletten** [comment]
@Ved111 Please provide a repo link to showcase where this happen if you want help.

**Comment by Ved111** [comment]
https://github.com/Ved111/ReactReader.git

The actual repo link I can't share because it is a part of intellectual property but I have made this repo link which contains the react-reader ebook component as used in the actual project. 

I am dynamically changing the URL of the ebook by passing the key value to the server , which in return gives back the pre-signed URL of the ebook stored in the s3 bucket. I am not able to open all the books via this method as I am getting no section found error.

Tell me if you need more details.

**Comment by gerhardsletten** [comment]
@Ved111 General speaking you should not copy the code in react-reader and paste them into your own project because then you will manually need to update this in future releases. Instead you should import the modules and use its public api described in the [Usage section](https://github.com/gerhardsletten/react-reader#usage)

The solution @kozec [referees to  here](https://github.com/futurepress/epub.js/issues/684#issuecomment-495931737) is to fix bad practices used in some epub-files. Sadly some epub-book contain errors (at lease old epub-files) [check of a validation-tool like this](https://github.com/chialab/epubchecker), and native epub-readers like Apples Books contain many fixes to handle difference cases. Epub.js which this library uses contain some fixes, but probably not as many as Apple Books.

So to apply this fix, you can use the `getRendition` prop which will give you the epub's rendition object, where you can hook into the inner of epub.js and fix this:

```jsx
<ReactReader
  url={localFile || DEMO_URL}
  title={localName || DEMO_NAME}
  location={location}
  locationChanged={this.onLocationChanged}
  getRendition={(rendition) => {
    const spine_get = rendition.book.spine.get.bind(rendition.book.spine);  
    rendition.book.spine.get = function(target) {
        const t = spine_get(target);
        console.log(t)
        while ((t == null) && target.startsWith("../")) {
            target = target.substring(3);
            t = spine_get(target);
        }
        return t;
    }
  }}
/>
```

**Comment by Ved111** [comment]
@gerhardsletten thanks for replying. I will take care of not copying code like that. Thanks for the advice. 
I did implement the fix, after applying the fix some of the epub files (which contains error as you said) started to render. 
But still, for some ebooks it's still not working. And after changing the URL to the ebook URL which is error-free, RR is not able to function properly. Sometimes it keeps showing the previously opened ebook even if the URL is changed and sometimes while changing the page via the menu it shows no section error.
I am using ebooks from gutenberg.
Also, I also thought of removing all the ebooks with error in my s3 using the epubchecker api, but I am getting some errors. Are you aware of any other ways to validate whether an ebook contains error or not?
Thanks for reading, and have a nice day.

**Comment by gerhardsletten** [comment]
@Ved111 For errors you maybe will need to wrap your app in a react error boundary, to catch and handle the error. In most cases uncatched errors in js will need a restart of the webapp. Will suggest that you first develop and ensure that your application work correct with epub-files you know is error-free, then you maybe will need to debug to find what is wrong with the epub-files that you still experience problems with.

**Comment by Ibnathism** [comment]
I was getting this error. It didn't work for some epubs even after adding the rendition. 

But It finally worked after I set the initial value of location to null and did some changes in the rendition.
Some thing like this: 

```js
getRendition={(rendition) => {
            const spine_get = rendition.book.spine.get.bind(
              rendition.book.spine
            );
            rendition.book.spine.get = function (target) {
              let t = spine_get(target);
              if (!t) {
                t = spine_get(target);
              }
              return t;
            };
          }}
```

**Comment by terzeron** [comment]
In many cases, the target variable must be either CFI string, number or string (as spine ID or href). Otherwise, the target variable should be handled as 'undefined'. But this may be not a sillver bullet for problems.

```
          rendition.book.spine.get = function (target) {
            var t = spine_get(target);
            if (!t) {
              t = spine_get(undefined);
            }
            return t;
          }
```

### spine.js
```
  /**
   * Get an item from the spine
   * @param  {string|number} [target]
   * @return {Section} section
   * @example spine.get();
   * @example spine.get(1);
   * @example spine.get("chap1.html");
   * @example spine.get("#id1234");
   */


  get(target) {
    var index = 0;

    if (typeof target === "undefined") {
      while (index < this.spineItems.length) {
        let next = this.spineItems[index];

        if (next && next.linear) {
          break;
        }

        index += 1;
      }
    } else if (this.epubcfi.isCfiString(target)) {
      let cfi = new _epubcfi.default(target);
      index = cfi.spinePos;
    } else if (typeof target === "number" || isNaN(target) === false) {
      index = target;
    } else if (typeof target === "string" && target.indexOf("#") === 0) {
      index = this.spineById[target.substring(1)];
    } else if (typeof target === "string") {
      // Remove fragments
      target = target.split("#")[0];
      index = this.spineByHref[target] || this.spineByHref[encodeURI(target)];
    }

    return this.spineItems[index] || null;
  }

```

**Comment by terzeron** [comment]
@gerhardsletten 
No, it's just a issue of a certain epub file and we need some exception handling. 
Thank you for this project very much.

**Comment by terzeron** [comment]
[epub.zip](https://github.com/gerhardsletten/react-reader/files/9724579/epub.zip)
This is a proprietary file. I'd delete this attachment after you download it.

**Comment by gerhardsletten** [comment]
@terzeron Thanks, have downloaded int now

**Comment by ntvviktor** [comment]
Actually I keep getting the error "No Section found, but I added the line   `renditionRef.current = rendition;` 
and it works although I havent figured why. 
```Typescript
getRendition={(rendition) => {
          //
          renditionRef.current = rendition;
          const spine_get = rendition.book.spine.get.bind(rendition.book.spine);  
          rendition.book.spine.get = (target: string) => {
              let t = spine_get(target);
              console.log(t);
              while ((t == null) && target.startsWith("../")) {
                  target = target.substring(3);
                  t = spine_get(target);
              }
             
              return t;
          }
        }}
```

**Comment by timsilber** [comment]
@gerhardsletten I am also experiencing this issue and have chased it down to certain EPUBs having varied directory structures of their OEBPS. if the XHTML files are directly in the OEBPS folder, the reader will load appropriately, but it they are in subdirectories (e.g. text/Introduction.xhtml) it will fail. do you have any recommendations on a fix? additionally, some books will append a an anchor link (e.g. OEBPS/xhtml/Chapter294.xhtml#sec20)

**Comment by gerhardsletten** [comment]
@timsilber Then it is something that need to be fixed in epubjs, this repo is only a react wrapper for epubjs.
