### ISSUE TITLE
epub rendering issue.

### ISSUE THREAD

**Issue by siddhudhangar** [gerhardsletten/react-reader#37]
I followed some steps to install react reader on mint system, that is as follows,
1. i ran this react reader installation command 
      npm install react-reader --save
2. I copied below code in my app.js file.
import React, { Component } from "react";
import { ReactReader } from "react-reader";

class App extends Component {
  render() {
    return (
      <div style={{ position: "relative", height: "100%" }}>
        {" "}
        // * Container needs a height..
        <ReactReader
          url={"/alice.epub"}
          title={"Alice in wonderland"}
          location={"epubcfi(/6/2[cover]!/6)"}
          locationChanged={epubcifi => console.log(epubcifi)}
        />
      </div>
    );
  }
}

after running server at http://localhost:3000 url, it rendered epub file with cover page. but it did not rendered epub pages when i clicked on each chapter from left navigation.
so i attached one screenshot for your reference. kindly check.

![screenshot from 2019-02-12 16-32-15](https://user-images.githubusercontent.com/31622143/52631596-31d5e280-2ee5-11e9-83d1-4f68b1d4c4b9.png)

**Comment by gerhardsletten** [comment]
In the console I see an error from a library named popover, it this something you have added yourself?

**Comment by goonursultan** [comment]
@gerhardsletten How can I add this block to reader

![image](https://user-images.githubusercontent.com/38785567/57757464-58d7c680-7717-11e9-9676-1caad3702d21.png)
