### ISSUE TITLE
No Section Found error

### ISSUE THREAD

**Issue by siddhudhangar** [gerhardsletten/react-reader#38]
When i tried to load my epub file through react reader, it was not working. In console it was showing me below error message.
Unhandled promise rejection Error: "No Section Found"
	_display http://localhost:3000/static/js/1.chunk.js:29432:27
	dequeue http://localhost:3000/static/js/1.chunk.js:33605:20
	run http://localhost:3000/static/js/1.chunk.js:33654:11
index.js:1446
d/console[e]
index.js:1446
onUnhandled/</result<
es6.promise.js:145
./node_modules/core-js/modules/_perform.js/module.exports
_perform.js:5
onUnhandled/<
es6.promise.js:136
./node_modules/core-js/modules/_invoke.js/module.exports
_invoke.js:7
<anonymous>
_task.js:47
run
_task.js:27
listener

I kept my all xhtml file into **OPS/Text** folder.but when i moved all xhtml files from OPS/Text folder to OPS (root)  folder and i updated  content.opf file also. then epub file was rendering and working properly. 

so i wanted to know that how to load or render all xhtml files from OPS/Text folder.
I attached two files such as measurement.zip file, this is original file and measurement (copy).zip file, this is modified file, after modification it was working. kindly check and let me know.

[measurement.zip](https://github.com/gerhardsletten/react-reader/files/2855858/measurement.zip)
[measurement (copy).zip](https://github.com/gerhardsletten/react-reader/files/2855859/measurement.copy.zip)

**Comment by gerhardsletten** [comment]
This is most likely a problem within the dependency epub-js and maybe variants over the official epub-standard. Check that your epub confirms to the standard and if the error is from epub-js
