### ISSUE TITLE
not working with typecript 

### ISSUE THREAD

**Issue by purusingh** [gerhardsletten/react-reader#39]
@types/react-reader is not found

**Comment by gerhardsletten** [comment]
I do not use typescript, but feel free to ad a PS for it

**Comment by dhiv-nitt** [comment]
@gerhardsletten how can we counter this ? was the PS created ?

**Comment by gerhardsletten** [comment]
Please add a PR for this

**Comment by HerbertHe** [comment]
follow my steps and you can use:

1. make a new file `declaration.d.ts` in your root directory
2. write sth.

```
declare module "react-reader" {
    const ReactReader: any
    const ReactReaderStyle: any
    export { ReactReader, ReactReaderStyle }
}
```
3. then, you can import the module in `.tsx`file

**Comment by HerbertHe** [comment]
And then you can use nearly all of js modules which are not supported ts by using this method.
