### ISSUE TITLE
Some epub can not open

### ISSUE THREAD

**Issue by 13141062188** [gerhardsletten/react-reader#4]
invalid input TypeError: invalid input
or
Could not load book at: undefined

**Comment by gerhardsletten** [comment]
Yes, it looks like the development of [epub.js v3](https://github.com/futurepress/epub.js/tree/v0.3) still is not ready, and this react-wrapper are depending of this to be stable before it would open all epub v2 files.

But you could try to fork this, and point the dependency of epub.js v3 branch directly to their repo and see it that would fix the issue with your books. If it do, send me a pull request and I will update.
