### ISSUE TITLE
SVG items in spine don't render correctly

### ISSUE THREAD

**Issue by turnerhayes** [gerhardsletten/react-reader#41]
If the spine contains a non-(X)HTML item (say, an SVG file), the content won't be displayed and a JS error will appear in the console.

See https://codesandbox.io/s/keen-fog-dlij1 for reproduction (you may need to open the output in a new window, and open DevTools).

The .epub file was taken from https://github.com/IDPF/epub3-samples

**Comment by gerhardsletten** [comment]
Maybe you will need to add the svg into a html-chapter and display it this way? Not sure if you can use something else than html-files in the spine.

**Comment by turnerhayes** [comment]
These samples come from the IDPF repo, which claims to be maintained by the W3C's EPUB 3 Community Group, which suggests that SVGs in spine is a valid use case. The spec indicates that the item refs need to refer to [publication resources](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html#dfn-publication-resource), which don't explicitly call out SVGs but does mention "images".

**Comment by gerhardsletten** [comment]
@turnerhayes Hi, then I think this need to be supported in epub.js and is not related to React Reader, so it is best if you create a pull-request there for support for this.
