### ISSUE TITLE
TOC uses incorrect refs

### ISSUE THREAD

**Issue by turnerhayes** [gerhardsletten/react-reader#42]
Reproduction sandbox: https://codesandbox.io/s/loving-dhawan-pl8z4

Open the TOC and click on one of the entries (e.g. Chapter 1)

Note that the following error appears in the console and the TOC item is not displayed:

```
rendition.js:397 Uncaught (in promise) Error: No Section Found
    at Rendition._display (rendition.js:397)
    at Queue.dequeue (queue.js:99)
    at queue.js:153
```

This seems to arise because it's trying to change location to `"fcla-xml-2.30li8.xhtml"`, but the key for it in `spineByHref` is `"xhtml/fcla-xml-2.30li8.xhtml"`

**Comment by gerhardsletten** [comment]
This is caused by the fact that the href is used as ref, but I guess if the same href is in the list there will be a dublicated key, updating to use the index in the array instead in next version published soon.
