### ISSUE TITLE
Some epub docs are not getting rendered by ReactReader component

### ISSUE THREAD

**Issue by sharan-satkhed** [gerhardsletten/react-reader#44]
Some epub docs are not getting rendered by ReactReader component and also it is not showing any errors in console.

Please find below sample .epub file which has the issue. Here am not able to upload directly .epub so compressed it to .zip.
 
[a00041476en_us_2.zip](https://github.com/gerhardsletten/react-reader/files/3338813/a00041476en_us_2.zip)

Page is coming up without doc content, below is the screenshot of the response.
![image](https://user-images.githubusercontent.com/42669952/60338368-5c6f9600-99c3-11e9-818f-86c3cb5af7e3.png)

Above .epub file is getting rendered by "EPUB File Reader" app and some other plugins also.

**Comment by sharan-satkhed** [comment]
Hi @gerhardsletten,
could you please look into this issue?

**Comment by gerhardsletten** [comment]
Hi @sharan-satkhed 

I am no expert in the epub-format, but there is probably something with your file, you will need to unzip it and compare its content with a epub that is working

**Comment by sharma0611** [comment]
In EpubView, when rendition is called without a location, it is called with toc[0].href. In some ebooks, this is sometimes nav.xhtml which then doesn't work. I believe it'd be better to just call rendition.display() in this scenario with no arguments.
