### ISSUE TITLE
Is it possible for people to highlight text in the reader?

### ISSUE THREAD

**Issue by naissa12** [gerhardsletten/react-reader#46]
Is it possible for people to highlight text in the reader?

**Comment by gerhardsletten** [comment]
See epub.js [example on with selection here](https://github.com/futurepress/epub.js/blob/master/examples/marks.html)

And see the the [demo-src in this repo](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js) for how to obtain the epubjs rendition-object

**Comment by Ved111** [comment]
@gerhardsletten So, if I understood correctly the code under the script tag [here](https://github.com/futurepress/epub.js/blob/master/examples/marks.html) should be added to the getRendition funtion code in [RR](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js) right?

**Comment by gerhardsletten** [comment]
Yes thats the same rendertition

**Comment by Ved111** [comment]
@gerhardsletten I implemented the changes like you said, but I am getting following error:

TypeError: contents.mark is not a function

I have done the following changes. 

`               rendition.on("selected", function(cfiRange, contents) {
                  var m = contents.mark(cfiRange, {'something' : true}, (e) => {
                    var bounds = e.target.getBoundingClientRect();
                    var clientX = e.clientX;
            
                    if (clientX > bounds.right) {
                      console.log("mark clicked", e.target);
                    }
                })
                contents.window.getSelection().removeAllRanges();
                });
              this.rendition.themes.default({
      'p': {
        'padding': '0 20px 0 0',
        'text-align': 'left',
        'position': 'relative'
      },
      '[ref="epubjs-mk"]::before' : {
        'content': '""',
        'background': 'url("data:image/......") no-repeat',
        'display': 'block',
        'right' : '0',
        'position' : 'absolute',
        'width': '20px',
        'height': '20px',
        'margin': '0',
        'cursor': 'pointer'
      }
    });

`
Can you help me with this error?

**Comment by gerhardsletten** [comment]
@Ved111 The example you linked to (marks.html) is pretty old (3 years), so I think that is for an older version of epubjs. Mayby you first need to check if it works with the current epubjs?

**Comment by mahdieh-sedaghat** [comment]
@gerhardsletten I installed the latest version of epubjs, but I still got the following error:
TypeError: contents.mark is not a function

Can you help me to fix that error?
