### ISSUE TITLE
Not working with S3 signed URL

### ISSUE THREAD

**Issue by MichaelSavin** [gerhardsletten/react-reader#49]
**Problem:** S3 signed URL isn't working with react-reader, but working with `epub.js` if you specify the type exactly using `openAs` property.
Signed URL looks like http://localhost:9001/public/5114fa60-190d-11ea-b37e-c35bb6f93bd3-9785969114302.epub?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191209%2F%2Fs3%2Faws4_request&X-Amz-Date=20191209T101525Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=47671c3524be30eb23c01e92895ae5adebd683fb885f42fe7320ccfc2b975660

**Solution:** the problem with a function `componentDidMount` in `
src/modules/EpubView/EpubView.js`. You need to send initial `epubOptions` props like `epubOptions={openAs: 'epub'}` but not an empty object.

**Comment by gerhardsletten** [comment]
Hi, I have added an epubInitOptions [mention in README](https://github.com/gerhardsletten/react-reader#epubview-props) you can use with ReactReader or EpubView that will make you control this property, so you should be able to do this:

```
<ReactReader
  epubInitOptions={{
    openAs: 'epub'
  }}
 ...
/>
```

Let me now if this fixes this issue
