### ISSUE TITLE
Updates to epub.js v0.3.7 breaks react-reader

### ISSUE THREAD

**Issue by ituaijagbone** [gerhardsletten/react-reader#5]
Will there be an update to react-reader as the new version of epub.js (0.3.7) breaks the reader. v0.3.7 with this error: `rendition.js:198 Uncaught TypeError: this.ViewManager is not a constructor`

**Comment by gerhardsletten** [comment]
@ituaijagbone Would you check to see if the latest updates have fixed this issue?

**Comment by ituaijagbone** [comment]
@gerhardsletten yes it has. I can close the issue now. Thanks.

**Comment by RareNCool** [comment]
What's the latest version of react-reader? An install gives me 0.10.0, and it still has this issue.

**Comment by gerhardsletten** [comment]
@RareNCool Yes, did forgot to push the latest update to github. The [demo should be updated](http://gerhardsletten.github.io/react-reader/) as well now. You are not running in some legacy browser?

**Comment by RareNCool** [comment]
@gerhardsletten Tested in Chrome v55.0.2883.87 m and Opera v42.0.2393.517. I was doing a `yarn add` from CL, should I be using what's here on GitHub instead?

**Comment by gerhardsletten** [comment]
Check your version of epubjs, if it has been a dependency of your project from before, it could be an older release. 

```
$  npm ls epubjs
react-reader@0.10.0 /Users/gerhard/dev/react-reader
└── epubjs@0.3.11 
```

**Comment by RareNCool** [comment]
EpubReader@0.0.1 C:\Users\Shawn\Documents\GitHub\epub-reader
`-- react-reader@0.10.0
  `-- epubjs@0.3.11

**Comment by RareNCool** [comment]
@gerhardsletten Here's the project, if it helps: https://github.com/RareNCool/epub-reader

**Comment by gerhardsletten** [comment]
@RareNCool Think you have a problem with webpack2, I see that if i downgrade to `webpack 1.12.11`in your lib, it builds. Then you will also need to wrap the reader in an div that has a defined height-property <div style={{height: '100%', position: 'relative'}}>...</div>

**Comment by RareNCool** [comment]
That did it, along with a downgrade of `webpack-dev-server`. Thanks!
