### ISSUE TITLE
How to track page changing ? 

### ISSUE THREAD

**Issue by MykolaSauliak** [gerhardsletten/react-reader#53]
Hi, 
I'm using react-reader library.
Is it possible to get notice when page change, so I can start read later from the specific place?

**Comment by gerhardsletten** [comment]
Hi @MykolaSauliak 

The `locationChanged` callback should be called everytime user changes his location within the epub, like when they click prev/next page or navigate in the chapter-navigation. In a webapp to persist the reading position, you would store this some place and then pass this value back in the `location` property

```
<ReactReader
  url={"/alice.epub"}
  title={"Alice in wonderland"}
  location={"epubcfi(/6/2[cover]!/6)"}
  locationChanged={epubcifi => console.log(epubcifi)}
/>
```

In the [simple sample app in this repo](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js#L80), you can see how is done to local-storage.
