### ISSUE TITLE
Using Hypothes.is in react reader

### ISSUE THREAD

**Issue by eshaw29** [gerhardsletten/react-reader#54]
So it appears as though hypothes.is is compatible with epub.js. Just curious if it is possible for us to access hypothes.is through react reader and if so how.

https://github.com/futurepress/epub.js/blob/master/examples/hypothesis.html

**Comment by gerhardsletten** [comment]
Hi @eshaw29 

There is a getRendition prop, see https://github.com/gerhardsletten/react-reader#epubview-props

But I am not sure if that will be enough in order to accomplish this, but you can add a pull-request if you need to access some other parts of the underlaying epubjs api.
