### ISSUE TITLE
prevent copy event 

### ISSUE THREAD

**Issue by Elessar1996** [gerhardsletten/react-reader#57]
How can I prevent copy events from the file which react-reader is showing? I set swipeable true to prevent the selection act. but now the user cannot scroll the book.

**Comment by mahmod2000** [comment]
I also have this problem

**Comment by mahmod2000** [comment]
I found a solution.

rendition.themes.default({
            'body': {
                '-webkit-touch-callout': 'none', /* iOS Safari */
                '-webkit-user-select': 'none', /* Safari */
                '-khtml-user-select': 'none', /* Konqueror HTML */
                '-moz-user-select': 'none', /* Firefox */
                '-ms-user-select': 'none', /* Internet Explorer/Edge */
                'user-select': 'none'
            }
        });

**Comment by paolodeste** [comment]
This is a good solution if you don't want to select text. If you need to preserve selection (for highlight purpose for example), is it possible to prevent copy events?

**Comment by gerhardsletten** [comment]
> How can I prevent copy events from the file which react-reader is showing? I set swipeable true to prevent the selection act. but now the user cannot scroll the book.

@Elessar1996 Are you using epubjs option to display a ebook with vertical scrolling, I think swipeable will not be compatible with that.

@mahmod2000 Why should a user be able to highlight something if they are not able to copy it?

It is maybe possible to hack the build in copy-event with js, but for most cases this is not something you want, so you will need to look into this yourself if the community can not help you.
