### ISSUE TITLE
Overriding styles on EpubView

### ISSUE THREAD

**Issue by mariacheline** [gerhardsletten/react-reader#58]
Hi, in the docs it says to override default on EpubView
you can just pass `styles` prop but doing so, not only breaks the rendering of the page but
also no styles are being applied.

**Steps to reproduce:**
Adding `styles` prop to EpubView

```javascript
<EpubView
    url={book.data.epub.file.uri}
    styles={{background: 'red'}}
/>
```
Any clarification on this?
Thank you 🙏🏼

**Comment by gerhardsletten** [comment]
@mariacheline You will need to import the basic styles and then extend it (it uses react style-attributes, ie object with css-properties), also take a look at the [used style to see what you can extend](https://github.com/gerhardsletten/react-reader/blob/master/src/modules/ReactReader/style.js)

```js
import { ReactReaderStyle } from "react-reader";

const newStyle = {
  ...ReactReaderStyle,
  container: {
    ...ReactReaderStyle.container,
    backgrondColor: "red"
  }
}

```
