### ISSUE TITLE
Update for new version of epubjs

### ISSUE THREAD

**Issue by alikazemkhanloo** [gerhardsletten/react-reader#60]
Hi,
I tried to update `epubjs` version in `package.json`. But I get `unexpected token 'export'` error message in my nextjs app.
Is it possible for you to update the dependency for `epubjs`? The new version has some fixes for rtl books. I don't know what else I need to do. 

Thanks.
Edit: the error is located in the last line in `epubjs/libs/mime/mime.js`. I manually edited and used `commonjs` format for exporting. still, I do not know how it is working in this package.

**Comment by gerhardsletten** [comment]
@alikazemkhanloo Will be fixed in a new version today, reopen this issue if this don't fix your problem.
