### ISSUE TITLE
Some S3 links works, but other don't

### ISSUE THREAD

**Issue by mrbonini** [gerhardsletten/react-reader#61]
Hey
I am having a problem where some S3 links works fine and I can render the EPUBs normally, but some links returns a Forbidden error and the link is not complete finishing with '/META-INF/container.xml'.

Working link seems like this
https://s3.sa-east-1.amazonaws.com/medcel.admin/pedagogical/books/5bd36de737a0784088c22cf4/CirurgiaGeralVol.2Extensivo2019.epub

not working link is very similar
https://s3.sa-east-1.amazonaws.com/medcel.admin/pedagogical/books/5ee7d7345a31d92a7d9f1ca5/pedagogicalbooks5ee7d7345a31d92a7d9f1ca5epubepub
This links returns this

Any ideia what could it be?

**Comment by gerhardsletten** [comment]
@mrbonini Don't know if it is a typo, but the file extension (.epub) is missing on the second url?
