### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by uma-08** [gerhardsletten/react-reader#62]
Is it possible to integrate DraftJs as a top layer on React-reader to enhance the functionality?
@gerhardsletten

**Comment by gerhardsletten** [comment]
@uma-08 React-reader is a wrapper for epub.js and there is a `getRendition` prop which is a callback that gives you access to the epub.js rendition object (from the README.md)

> Additional props will be passed to the underlaying EpubView component, like url, location, epubOptions, epubInitOptions and *getRendition*.

The way epub.js work is that is create an iframe where the html-content from the current chapter of the epub-file is displayed in, so you would need to inject stuff into this to add extra interactive things inside there.

Take a look at this example on how to add extra js and stuff to the content displayed within the iframe:
[https://github.com/futurepress/epub.js/blob/master/examples/annotator.html#L67](https://github.com/futurepress/epub.js/blob/master/examples/annotator.html#L67)

But  I am not sure if loading a react-bundle with Draft-js inside the iframe is a good idea, it might be performance issues doing so. I would suggest injecting buttons and when a user click those you can display an edit-dialog in your own app (where react-reader also is living) to accomplish this
