### ISSUE TITLE
How can I know if it is the last page

### ISSUE THREAD

**Issue by Rotten-LKZ** [gerhardsletten/react-reader#69]
How can I know if it is the last page?

And how do I calculate the percentage of reading now?

Thank you

**Comment by gerhardsletten** [comment]
@Rotten-LKZ Its only possible to get the current page and total page of the current chapter you are viewing:

You can get access to the inner details of epubjs with the `getRendition` callback,  see how this is done in [src/App.js](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js).

Store this in a instance-variable and use it in the `onLocationChanged` callback:

```
onLocationChanged = location => {
    console.log(this.rendition)
    this.setState(
      {
        location
      },
      () => {
        storage && storage.setItem("epub-location", location);
      }
    );
  };
```
Within the book->spine object you get access to the whole spine:

![image](https://user-images.githubusercontent.com/63344/95556756-13a2eb80-0a14-11eb-8f9e-471091f7b538.png)

And in the location-object you find the location of the current chapter:

![image](https://user-images.githubusercontent.com/63344/95556908-54026980-0a14-11eb-881b-36fdb52ab170.png)

But I think it should be possible to have the epub analysed be a nodejs service and run trough each chapter to extract number of chars it each, and then you could push this back to the client-side and use this together with the chapter-info to display some kind of total progress
