### ISSUE TITLE
Adding React-Reader in NextJS doesn't work

### ISSUE THREAD

**Issue by garytron** [gerhardsletten/react-reader#72]
# Bug report

## Description

I installed react-reader to my NextJS project (as a new project) but when I run the project in dev mode. I have the following:
 
**node_modules\epubjs\libs\mime\mime.js:169
export default { lookup };**

## To Reproduce

1. Install library `npm install react-reader --save`
2. Copy [example](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js) into pages/index.js
3. Run project `npm run dev`

## Screenshots

![image](https://user-images.githubusercontent.com/23147179/97529863-76820580-1976-11eb-8371-3156e113807b.png)

## System information

- OS: Windows 10
- Version of Next.js: 9.5.5
- Version of Node.js: 12.13.1
- Version of react-reader: 0.19.0

## Additional context

I attach my package.json
![image](https://user-images.githubusercontent.com/23147179/97589600-5167b400-19c3-11eb-8767-a73e807a9232.png)

Thanks in advance!

**Comment by garytron** [comment]
> 
> # Bug report
> ## Description
> 
> I installed react-reader to my NextJS project (as a new project) but when I run the project in dev mode. I have the following:
> 
> **node_modules\epubjs\libs\mime\mime.js:169 export default { lookup };**
> ## To Reproduce
> 
>     1. Install library `npm install react-reader --save`
> 
>     2. Copy [example](https://github.com/gerhardsletten/react-reader/blob/master/src/App.js) into pages/index.js
> 
>     3. Run project `npm run dev`
> 
>     4. See error
> 
> 
> ## Screenshots
> 
> If applicable, add screenshots to help explain your problem.
> ![image](https://user-images.githubusercontent.com/23147179/97504567-bcba7300-193c-11eb-993c-20a4d7fa1b4c.png)
> ## System information
> 
>     * OS: Windows 10
> 
>     * Version of Next.js: 9.5.5
> 
>     * Version of Node.js: 12.13.1
> 
>     * Version of react-reader: 0.19.0
> 
> 
> ## Additional context
> 
> I attach my package.json
> ![image](https://user-images.githubusercontent.com/23147179/97529863-76820580-1976-11eb-8371-3156e113807b.png)
> 
> Thanks in advance!

**Comment by adilier** [comment]
I think it's because next.js uses server side rendering, so you can't access the browser functionality without disabling ssr

[try using dynamic import: https://nextjs.org/docs/advanced-features/dynamic-import](https://nextjs.org/docs/advanced-features/dynamic-import)
[example: https://codesandbox.io/s/fervent-chatterjee-69vv7?file=/pages/index.js](https://codesandbox.io/s/fervent-chatterjee-69vv7?file=/pages/index.js)

**Comment by gerhardsletten** [comment]
@garytron Did @adilier comment work for you?

The error looks like a its related to the ES6 Module syntax, and I am not sure how nextjs support that. But anyway there is no reason to try to render the e-pub server-side, so like @adilier says this should be moved to client-side only. A simple useMounted hook can be used to force a rerender on client

```
import { useEffect, useState } from 'react'

function useMounted() {
  const [mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
  }, [setMounted])
  return mounted
}

const MyReader = () => {
  const mounted = useMounted()
  return (
    <div>
      {mounted && <ReactReader … />}
    </div>
  )
}
```

**Comment by hamidrezaborghei** [comment]
> 
> 
> I think it's because next.js uses server side rendering, so you can't access the browser functionality without disabling ssr
> 
> [try using dynamic import: https://nextjs.org/docs/advanced-features/dynamic-import](https://nextjs.org/docs/advanced-features/dynamic-import)
> [example: https://codesandbox.io/s/fervent-chatterjee-69vv7?file=/pages/index.js](https://codesandbox.io/s/fervent-chatterjee-69vv7?file=/pages/index.js)

Thanks Worked
