### ISSUE TITLE
It has some way to add annotations?

### ISSUE THREAD

**Issue by trolliama** [gerhardsletten/react-reader#73]
Can i add, remove or edit annotations with this wrapper?

**Comment by gerhardsletten** [comment]
Hi @trolliama It has been asked in earlier issues, so you can see if you find some direction there. One day I have some time I will try to add some more examples to the demo.

**Comment by gerhardsletten** [comment]
@trolliama I have added an example where [hightlight-selection-in-epub](https://github.com/gerhardsletten/react-reader#hightlight-selection-in-epub)

**Comment by trolliama** [comment]
thanks!
