### ISSUE TITLE
Epub display all squeezed together

### ISSUE THREAD

**Issue by timotech** [gerhardsletten/react-reader#75]
I think there is a problem with the styling of the react-reader component, its not displaying the full epub file, a lot of the display is hidden, only the toc part is showing with zero height, showing scroll bars without any height. The reading part is not showing at all. 
On inspecting the html, there are a lot of height: 0px in the mark-up.
Please look into it.

Thanks

![react-reader](https://user-images.githubusercontent.com/17544481/100384765-3ff4e480-3021-11eb-8905-f7f28fc27547.jpg)
Tim

**Comment by gerhardsletten** [comment]
@timotech [https://gerhardsletten.github.io/react-reader/](https://gerhardsletten.github.io/react-reader/) also runs the latest version, so you should check if it is working there, if it does, then there error is in your implementations

**Comment by timotech** [comment]
Hi Gerhard,
Thanks for your reply, i initially sent you a mail, i guess you have not seen it.
Actually, i don't know what i did wrong.
First i did npx create-react-app react-reader-client
Then i ran it and it displayed the initial react page
Then i deleted the code in the app.js file and replaced with the one below:
`import React, { Component } from "react";
import { ReactReader } from "react-reader";

class App extends Component {
  render() {
    return (
      <div style={{ position: "relative", height: "100%", width: "100%" }}>
        {" "}
        {/* Container needs a height.. */}
        <ReactReader
          url={"/alice.epub"}
          title={"Alice in wonderland"}
          location={"epubcfi(/6/2[cover]!/6)"}
          locationChanged={(epubcifi) => console.log(epubcifi)}
        />
      </div>
    );
  }
}

export default App;`

ran my project and started getting the image above.
Please help me out, i really don't know where the problem is.
Thanks

**Comment by gerhardsletten** [comment]
@timotech Try to change location to {0} which will render the first chapter, if the epubcfi you pass is not found by epubjs it will not render anything

```
<ReactReader
url={"/alice.epub"}
title={"Alice in wonderland"}
location={0} // <-- this
locationChanged={(epubcifi) => console.log(epubcifi)}
/>
```

**Comment by timotech** [comment]
Thanks Gerhard,
I just did that, 
<ReactReader
url={"/alice.epub"}
title={"Alice in wonderland"}
location={0} // <-- this
locationChanged={(epubcifi) => console.log(epubcifi)}
/>
Same result.
I'm thinking of re-creating the react app, then try all over again

**Comment by gerhardsletten** [comment]
@timotech You could try to publish it to your github, and then I could take a look. Btw, did you add the epub `alice.epub` into your project?

**Comment by timotech** [comment]
Yes, i will publish it now. Actually, when i used the code on your github, everything works fine. But when i published to my windows domain hosting it was not showing, it was complaining of the path www.mydomain.com/react-reader. So i decided to do a new react app, so that i can just type www.mydomain.com without the react-reader part, but now, its not displaying well locally.
I will publish it to github now and give you the path.
Thanks

**Comment by timotech** [comment]
Hi Gerhard,
Please check the github link below. Thanks
https://github.com/timotech/my-react-epub-reader

**Comment by timotech** [comment]
Hi Gerhard,
Thanks for your help
Any update please
Thanks

**Comment by gerhardsletten** [comment]
@timotech Checked out your example, and the problem is that your parent div with height and width set in procent dont work because you have not set a height for the body-tag, so either you can add a height/width to the body-tag, or you can use the vw and vh units for css on the wrapper to force the same height as the window.

```
<div style={{
  position: "relative",
  height: "100vh", // <-- this
  width: "100vw" // <-- and this
}}>
  <ReactReader
    url={"/alice.epub"}
    title={"Alice in wonderland"}
    location={0}
    locationChanged={(epubcifi) => console.log(epubcifi)}
  />
</div>
```

**Comment by timotech** [comment]
Wow Gerhard,
Thanks a lot, I didn't think it this way.
I don't want to be Oliver Twist, but I just wanted to ask, if I wanted to put a flip effect, how can I do it. Thanks

**Comment by gerhardsletten** [comment]
@timotech React reader is a wrapper of https://github.com/futurepress/epub.js/ and I am not sure if that support that kind of visual indication of going to prev/next page. Check out their issues maybe

**Comment by timotech** [comment]
Ok Thanks Gerhard, you have been so much help
