### ISSUE TITLE
Failed prop type: Invalid prop `url` supplied to `EpubView`

### ISSUE THREAD

**Issue by mbret** [gerhardsletten/react-reader#77]
When using `blob` which are valid, this warning shows up.

Would it be fair to add a new prop type here https://github.com/gerhardsletten/react-reader/blob/master/src/modules/EpubView/EpubView.js#L150 ?

**Comment by gerhardsletten** [comment]
@mbret It it works with `PropTypes.instanceOf(Blob)` you are welcome to add it as a PS
