### ISSUE TITLE
react reader question

### ISSUE THREAD

**Issue by sadam1807** [gerhardsletten/react-reader#78]
@gerhardsletten  I have a few questions, please answer
   1. how I can change the font-size , I tried using styles props but it's breaking the entire UI, please provide an example.
   2. How I can make it scrollable instead of the next and prev button.
   3. Aws s3 bucket signed URLs are not working with this libraries 

please help

**Comment by gerhardsletten** [comment]
Hi @sadam1807 

1. The "style props" is just for the react wrapper, you will need to look into the underlaying iframe from epubjs to change the font-size. You connect with epubjs through the `getRendition` props, and in the callback take a look at `rendition.current.themes.fontSize`

2. To make it scrollable you will need to look into the epubOptions prop, see readme for more info.

3. Look through previous issues, there was some other having trouble with s3 hosting, mayby he can help you
