### ISSUE TITLE
Uncaught (in promise) TypeError: json.map is not a function

### ISSUE THREAD

**Issue by jm2242** [gerhardsletten/react-reader#8]
First of all, thanks for this library, this is so awesome. I'm really excited to use it. 

I'm trying to get the following example to work:
```
import React, { Component } from 'react';
import { ReactReader } from 'react-reader'

class Reader extends Component {
  render() {
    return (
      <div style={{position: 'relative', height: '100%'}}>
        <ReactReader
          url={'https://s3-eu-west-1.amazonaws.com/react-reader/alice.epub'}
          title={'Alice in wonderland'}
          location={'epubcfi(/6/2[cover]!/6)'}
          locationChanged={(epubcifi) => console.log(epubcifi)}
        />
      </div>
    )
  }
}


export default Reader
```

I'm using Facebook's create-react-app. Upon navigating to the route which loads this component, I get the following error:

![image](https://cloud.githubusercontent.com/assets/8572502/24435646/9954d784-1404-11e7-8ab0-e6cc828f8761.png)

I'm already importing `babel-polyfill` in my `index.js`. Am I missing something silly?

**Comment by gerhardsletten** [comment]
Hi @jm2242 

Check to see if you have the latest version av react-reader which have epubjs#0.3.22 as dependency, there was published an version of epubjs earlier this week which contained an error.

**Comment by jm2242** [comment]
That was it! Thanks!
