### ISSUE TITLE
View is rendered without content

### ISSUE THREAD

**Issue by superkruger** [gerhardsletten/react-reader#80]
Followed instructions to create new project.
View renders without any epub content.

When changing parent div to "absolute", menu can be seen, but still no content.

Example project: https://github.com/superkruger/reader-app

**Comment by superkruger** [comment]
This is output in the console:
No startContainer found for epubcfi(/6/2[cover]!/6) - epubcfi.js:931

**Comment by ErnestGrey** [comment]
@superkruger I was having this issue as well. It seems like the `<iframe>` within `<div class="epub-view">` has a height of 0. If I give that element a height in the inspector then the content shows up. However, if I give a height to the parent `<div>` wrapping the `<ReactReader>` the menu shows up, but I don't see any content. I've followed the example and the demo and I can't seem to figure out how to get the content to show with styling on the parent <div>`. Any help with this would be great....maybe I am missing something?

**Comment by ErnestGrey** [comment]
Actually, it's not just the <iframe> it's several divs  wrapping that element that have a height of 0. It seems like the height isn't being inherited for some reason.

**Comment by ErnestGrey** [comment]
I cloned the project and ran it locally and no content is showing. Anyone else having this issue too?
![Screen Shot 2021-01-25 at 9 46 57 AM](https://user-images.githubusercontent.com/1953040/105721389-83b97c80-5ef2-11eb-9d5a-949c15ea1b3e.png)

**Comment by superkruger** [comment]
I've tried another wrapper implementation (https://github.com/cnscorpions/react-epub-reader), same result.

Eventually just decided to use the epubjs own express based version (https://github.com/futurepress/epubjs-reader) and modify that...

**Comment by ErnestGrey** [comment]
I found this issue, at least for me, it has to do with the last commit [here](https://github.com/gerhardsletten/react-reader/commit/53bf2ef2651a8b44c4e8ce31dbc5d42bc6aa1cf6). If you remove the `styles` prop from `<EpubView>`, you will see the content.

**Comment by gerhardsletten** [comment]
@superkruger @ErnestGrey Sorry, there was a PR that I did not checked enough, but its fixed now in `react-reader@0.20.3`

**Comment by quocdat-le-insacvl** [comment]
Hi, 
I'm new to React and web dev. I encounter the same error above. Here's my setup : 
```
import React from "react"
import { ReactReader, ReactReaderStyle } from "react-reader"

interface EpubViewerProps {
  url: string
  location: string | number
  setLocation: (location: string) => void
}

export function EpubViewer({ url, location, setLocation }: EpubViewerProps) {
  return (
    <div style={{ height: "100%", position: "relative" }}>
      <ReactReader
        url={url}
        location={location}
        locationChanged={(epubcfi: string) => setLocation(epubcfi)}
        epubOptions={{
          allowPopups: true,
          allowScriptedContent: true,
        }}
        epubInitOptions={{
          openAs: 'epub',
        }}
      />
    </div>
  )
}
```

**Comment by quocdat-le-insacvl** [comment]
Oh I got it. The epub need to be DRM free.
