### ISSUE TITLE
Problem with highlighting text in the reader

### ISSUE THREAD

**Issue by mahdieh-sedaghat** [gerhardsletten/react-reader#81]
I saw the same issue that was closed, but I still faced this issue. I followed the instruction provided in this [example](https://github.com/futurepress/epub.js/blob/master/examples/marks.html) to implement text highlighting. Also, I updated epubjs to the latest version, but I got the following error:
TypeError: contents.mark is not a function

Can anyone help me to fix this error?

**Comment by sepiddd** [comment]
I have faced this issue too. :( @gerhardsletten

**Comment by sunny8751** [comment]
Try adding a highlight annotation on the cfi:
```
rendition.on("selected", (cfiRange) => {
      console.log(rendition.getRange(cfiRange).toString());
      rendition.annotations.add("highlight", cfiRange);
})
```

**Comment by gerhardsletten** [comment]
@mahdieh-sedaghat @sepiddd

Thanks for your sample @sunny8751, I have also updated the README with more sample on what people often ask for, so see [hightlight-selection-in-epub](https://github.com/gerhardsletten/react-reader#hightlight-selection-in-epub)
