### ISSUE TITLE
Image display problem on mobile phones

### ISSUE THREAD

**Issue by cryptoprof** [gerhardsletten/react-reader#82]
Hi, thanks for the great project!
In the example, https://gerhardsletten.github.io/react-reader/, when I switch to developer mode and select mobile, parts of the images are displayed on the next page.
![image](https://user-images.githubusercontent.com/15214242/107210433-2c98c900-6a15-11eb-90db-05fc99db3c2a.png)
I tried to fix it by adding styles, but looking at the code, I realized that they are bound to the reader controls and the next code code doesn't make sense:

```js

  render () {
    const { location } = this.state;
    const newStyle = {
      ...ReactReaderStyle,
      img: {
        width: "100%",
      }
    }
    const localUrl=require('./alice.epub'); //Desktop
    return (
      <div style={{
        height: "100vh",
        width: "100vw",
        position: "relative",
      }}>
          <ReactReader
            fullscreen={true}
            url={localUrl}
            title={"Test book"}
            location={location}
            styles={newStyle}
            locationChanged={this.onLocationChanged}
            getRendition={this.getRendition}
          />
    </div>    
    )
  }
```
Can we somehow append styles to objects in book?

**Comment by gerhardsletten** [comment]
@cryptoprof The style-props for react-reader only apply to the react-elements wrapping the epubjs iframe, so to apply your own styles to the epub inside the iframe you need to use the `getRendition` callback prop to get access to the [epubjs rendition object](http://epubjs.org/documentation/0.3/#rendition)

```jsx
<ReactReader
  url={localPath}
  title={tittel}
  getRendition={(rendition) => {
    rendition.themes.register('custom', {
      img: {
        'max-width': '100%;',
        height: 'auto !important'
      }
    })
    rendition.themes.select('custom')
  }}
/>
```

**Comment by cryptoprof** [comment]
Thank you again! Awesome!
