### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by rsunbabu** [gerhardsletten/react-reader#84]
I couldnt see the filter feature; is there any functionality set to enable this?

**Comment by gerhardsletten** [comment]
Hi @rsunbabu 

If you would like to create a search functionality in your epub-reader, you would most likely need a server backend that can index the epub files you offer. React reader is a react-wrapper for [epub.js](https://github.com/futurepress/epub.js/) and to my knowledge it does not support searching directly (clientside) in the whole epub-file.

I am no expert in writing the core logic of a search, but epubjs (and react reader) uses [EpubCFI](http://epubjs.org/documentation/0.3/#epubcfi) to navigate to different parts of a book, so if your search-backend would need to deliver this back and then you can pass it into the `location` prop for ReactReader to let the user navigate to the part they searched for.

**Comment by rsunbabu** [comment]
Thank you
