### ISSUE TITLE
How to get current page and total number of page ?

### ISSUE THREAD

**Issue by qtv100291** [gerhardsletten/react-reader#85]
Hello, I would like to ask about how to get current page number and total number of page .
In your section ReactReader props, there is a prop :  

> locationChanged [func] - a function that receives the current location while user is reading 

but the current location returned is in under form like epubcfi(/6/8[chapter_001]!/4/2/16/3:14), How can I get page number from this text ?

**Comment by gerhardsletten** [comment]
@qtv100291  Since you would need to render a dom-element to know its width/height, epubJS only knows how many pages your current chapter is (its web-based) based on your viewport. Take a look here go get the visible page of the current chapter here #69

**Comment by gerhardsletten** [comment]
@qtv100291 I have also added an example here: [display-a-scrolled-epub-view](https://github.com/gerhardsletten/react-reader#display-a-scrolled-epub-view)
