### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by nycynik** [gerhardsletten/react-reader#89]
I'm trying to use this in a new project, but it fails with "global is not defined"

I've tracked it down to this line: 

`global.ePub = Epub; // Fix for v3 branch of epub.js -> needs ePub to by a global var`

in this file https://github.com/gerhardsletten/react-reader/blob/3c605061e81da8792435e232e8868fea9dda70b3/src/modules/EpubView/EpubView.js 

I'm not using the exact syntax from the readme, and I suspect that is the issue, is `global` defined for React components?

In any case, I'm importing it like so:

```
import {
  EpubView, // Underlaying epub-canvas (wrapper for epub.js iframe)
  EpubViewStyle, // Styles for EpubView, you can pass it to the instance as a style prop for customize it
  ReactReader, // A simple epub-reader with left/right button and chapter navigation
  ReactReaderStyle, // Styles for the epub-reader it you need to customize it
} from 'react-reader';

export function ContentRead(props: ContentReadProps) {
  return (
    <div>
      <h1>Welcome to content-read!</h1>
      <ReactReader
          url={"/assets/pubs/alice.epub"}
          title={"Alice in wonderland"}
          location={"epubcfi(/6/2[cover]!/6)"}
          locationChanged={epubcifi => console.log(epubcifi)}
      />
    </div>
  );
}
```

Any thoughts about this one?

**Comment by nycynik** [comment]
In true "let's see if we can get this to work" form. I went ahead and tried to define global.

```
if (!global) var global = Window;
global.ePub = _index.default; // Fix for v3 branch of epub.js -> needs ePub to by a global var

```

it almost worked, the epub view now renders, the TOC `=` button shows up and can be clicked, but it never actually loads the epub. (Of course, I suspect that is because it can't find the ePub defined on Window.

**Comment by gerhardsletten** [comment]
@nycynik Fixed in your PR, thanks
