### ISSUE TITLE
How to add dark mode and scrolled view?

### ISSUE THREAD

**Issue by paras205** [gerhardsletten/react-reader#91]

**Comment by gerhardsletten** [comment]
@paras205 When I wrote it, I choose to use react basic styles for a non specific styling solution, see [src/modules/ReactReader/style.js](https://github.com/gerhardsletten/react-reader/blob/master/src/modules/ReactReader/style.js) 

But you can overwrite some of them with own css-rules in the `styles` prop.

To make in scrolled, pass this into epubOptions prop

```
<ReactReader
  epubOptions={{
    flow: "scrolled"
  }}
/>

**Comment by heymartinadams** [comment]
Congrats, Gerhard! How lovely! All best to you and your family ✨
