### ISSUE TITLE
Hide contextmenu on mobile and show custom options menu after highlight 

### ISSUE THREAD

**Issue by nvuhung** [gerhardsletten/react-reader#93]
Hello, I want to hide the default context menu on mobile web:
![image](https://user-images.githubusercontent.com/11483168/132595897-adfd8270-5a70-4e0a-bc34-c67535b95762.png)

Then show the custom options menu above the selected text

![image](https://user-images.githubusercontent.com/11483168/132596379-137c13cb-4e86-48de-8090-f6ac364e65e5.png)

Do you have an idea?

**Comment by gerhardsletten** [comment]
@nvuhung Take a look at this [SO-answer](https://stackoverflow.com/questions/16039219/disable-selection-context-menu-in-ios-safari).

You will need to apply this css-rule inside the iframe epubjs render to by following [this recipe](https://github.com/gerhardsletten/react-reader#add--adjust-custom-css-for-the-epub-html) for React reader
