### ISSUE TITLE
Changing fontSize is not affecting highlight

### ISSUE THREAD

**Issue by Brenw10** [gerhardsletten/react-reader#94]
I'm facing an issue related to highlight and fontSize.
Basically when I select a text and then change the fontSize, the highlight still on the same place.

https://user-images.githubusercontent.com/20256448/132882300-ac007ed0-2c84-41a4-af28-a85f77b85dea.mp4

To fix this issue I have created a repaint function (workaround) that executes after fontSize changes, this function removes and adds the highlights again.

**Comment by Hadi87s** [comment]
@Brenw10 can you please send me the workaround's code? I'm having this exact same issue
