### ISSUE TITLE
Problem with loading custom fonts

### ISSUE THREAD

**Issue by fkazemi5236** [gerhardsletten/react-reader#95]
There is no ability to add fonts in this package. Images are displayed irregularly on mobile pages and are not appropriate

**Comment by gerhardsletten** [comment]
@fkazemi5236 The epub-file is a zip of html-documents that can contain custom css and fonts if the publishers added it. Take a look at this [recipe on how you can override the inner css](https://github.com/gerhardsletten/react-reader#add--adjust-custom-css-for-the-epub-html) of an epub. 

For both safety and to avoid styles bleed in or of of the epub-file, epubjs which this library wraps, render the epub inside an iframe, so you will not be able to place a custom font-file inside the epub-file, but it could be that you will be able to load the font-file from an url, but it could be that there are cors issues with this

**Comment by fkazemi5236** [comment]
tnks
I tried so hard. I was able to add to that style using the override method
like this:
rendition.themes.override('color' , '#424242')

**Comment by fkazemi5236** [comment]
There is no way to add fonts from Google. In this style writing model, font-face cannot be inserted

**Comment by gerhardsletten** [comment]
@fkazemi5236 Maybe you could look in issues for epubjs, see [one resent issue about fonts there](https://github.com/futurepress/epub.js/issues/788)

**Comment by josejuansanz** [comment]
Hi,

I know this is closed, but I had the same problem and found a solution. I've used the [Web Font Loader](https://github.com/typekit/webfontloader) library, which allows us to load fonts from different providers (Google fonts included) and it has a configuration parameter to inject the fonts into an [iframe](https://github.com/typekit/webfontloader#iframes).

So, what I've done is to use this library to load the fonts I want once the epub has been rendered:
`
getRendition={async (rendition) => {
  rendition.on('rendered', () => {
    WebFont.load({
      google: {
        families: ['Droid Sans', 'Droid Serif']
      },
      context: window.frames[0],
    });
  });
}};
`

Hope this helps.
