### ISSUE TITLE
how we can have singleView of epub in this package?

### ISSUE THREAD

**Issue by fkazemi5236** [gerhardsletten/react-reader#96]
how we can have singleView of epub in this package?

**Comment by gerhardsletten** [comment]
@fkazemi5236 Could you please try to explain what are you meaning?

**Comment by fkazemi5236** [comment]
It shows me a page on the left and a page on the right.
I need only one page in the middle

**Comment by gerhardsletten** [comment]
@fkazemi5236 You can pass options to [epubjs rendition](http://epubjs.org/documentation/0.3/#rendition) with `epubOptions` prop. See also [another epubjs doc here](https://github.com/futurepress/epub.js/blob/master/documentation/md/API.md#spread-1)

```
<ReactReader url=".." epubOptions={{spread: 'none'}} />
```
