### ISSUE TITLE
direct link url from google drive

### ISSUE THREAD

**Issue by Benjamim-EP** [gerhardsletten/react-reader#99]
I'm trying to load an epub directly from my drive, which is shared and with the direct download link

https://drive.google.com/uc?export=download&id=144DnWARzAslwNfCu8Cr0lpUtqBMJdATY

however it stays on the loading screen... , does the link extension need to have '.epub' at the end? as in the example
https://gerhardsletten.github.io/react-reader/files/alice.epub

I also needed to use an extension for CORS from the example file, is there how to configure react to allow CORS or does the browser need to be configured?

**Comment by gerhardsletten** [comment]
@Benjamim-EP First up, your url gives a 404, but also see [#handling-missing-mime-types-on-serve](https://github.com/gerhardsletten/react-reader#handling-missing-mime-types-on-server)

```sh
curl -I "https://drive.google.com/uc?export=download&id=144DnWARzAslwNfCu8Cr0lpUtqBMJdATY"
HTTP/2 404 
content-type: text/html; charset=UTF-8
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
```

**Comment by gerhardsletten** [comment]
@Benjamim-EP Also if google drive not allowing setting custom cors, I would write a in between service on Vercel to fetch and forward the request with correct cors headers. Neither react or the "browser" is able to override how a file from an external server is delivered
